spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online-store-demo
    username: tyler
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #Use create-drop to drop db after every session
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
secrets:
  SECRET_KEY: "452948404D635166546A576E5A7234753778214125442A462D4A614E64526755"